### PR TITLE
Added frontend files with the erb extension

### PR DESCRIPTION
**Pull request by trevunderwood**
Creating this pull request to merge front end files together.

### CODE REVIEW

**Review by TrevorHatch — DISMISSED** [review]
follows team coding standards.

**Comment by TrevorHatch** [comment]
follows team coding standards even more now

**Review by TrevorHatch — DISMISSED** [review]
good standards followed. impressive stuff

**Comment by trevunderwood** [comment]
Merge conflicts fixed. Awaiting approving review.

**Review by rampang — APPROVED** [review]
Approved passes tests and follows standards

**Pull request closed without merging**
